### ISSUE TITLE
Governance: Migrate and Updates.

### ISSUE THREAD

**Issue by P1R** [DECENTRALIZEDCLIMATE/docs#27]
## ToDo

![Image](https://user-images.githubusercontent.com/706259/234662519-52201d36-60f6-418d-b088-d6cda059a804.png)

Img1.

Perform the following tasks in the DCF DIRECTORY, Governance section Img1.

###  DAO Development Section

- [ ] Migrate Phase 0 from hackmd to Docs as a post (show the post)
- [ ] Change [Phase1, Network] string from `Ethereum Main / Goerli` to Ethereum Main / Snapshot`

### Decentralized Climate Improvement Proposals Section

![Image](https://user-images.githubusercontent.com/706259/234664380-2a4a1756-b898-4362-bb94-8c6dad55a58d.png)

Img2.

- [ ] Follow the DCIP Standard table to display DCIPs show same way as in img2. This is to change the Number, Titles and Authors as in Img2 or the DCIPs website.
- [ ] Change links of the dcips from hackmd to the dcip website, example: number 2 points to   https://dcips.decentralizedclimate.org/dcips/dcip-2
