### ISSUE TITLE
Reorganize book-summary

### ISSUE THREAD

**Issue by P1R** [DECENTRALIZEDCLIMATE/docs#9]
## Reorganize the `book-summary`:

- [ ] set Default page to[ DCF Documents Directory](https://hackmd.io/YP4DnMt5R1y-Z3h9zjjcMQ)
  - [ ]  Deploy all the DCF DOCS Directory from hackmd to this repository as a post with a permLink just as we did with the readme.
  - [ ]  The post SHOULD be shown on the book summary As DCF DIRECTORY
  - [ ] Rename DCF DOCS to DCF DIRECTORY

- [ ] Make a post for the[ Social Services Directory](https://hackmd.io/iFoqmVpYTV-1Wn5Mfio_6A)
  - [ ] Deploy all the DCF DOCS Directory from hackmd to this repository as a post with a `permaLink` just as we did with the readme.
  - [ ]  The post SHOULD be shown on the book summary "Post Section" (Shown in Img 1.) As DCF DIRECTORY
  - [ ]  Rename DCF DOCS to DCF DIRECTORY
  - [ ] Tthe posts SHOULD NOT be shown on the book summary

![Image](https://user-images.githubusercontent.com/706259/226971684-7641f4ea-6080-4d2d-b073-fa8db92f8b4d.png)
Img. 1.  book summary "Post Section" 

- [ ] Change Link Fork it now! to our docs repository.

- [ ] Decentralize readme
  - [ ] create a directory at assets named `posts` FOR posts and a subdirectory with the post name (do not put the post extension).
  - [ ] Store the post images in the subdirectory with the post name and integrate (link) into the post file.
  - [ ] Add readme before fork it Now! in the same section.

- [ ] Fix the favicon display telegram in the top right of the docs site.

##  ToDo.

* Display Document Index FROM THE viewed document (`page-wrapper `) AT the left  `book-summary` (or create the viewed document index in the right or top of the `page-wrapper `). 
* Fix the favicon share in the top right of the docs site. to copy link for this website link: `https://docs.decentralizedclimate.org`
